const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2347080936288";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_16_26_09_22_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMCxcbiAgICAgICAgMTQ3LFxuICAgICAgICAyLFxuICAgICAgICAyMzIsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMTMsXG4gICAgICAgIDk5LFxuICAgICAgICAxNTcsXG4gICAgICAgIDUsXG4gICAgICAgIDQsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMjI3LFxuICAgICAgICAyMzksXG4gICAgICAgIDYsXG4gICAgICAgIDg0LFxuICAgICAgICA2NSxcbiAgICAgICAgMTAxLFxuICAgICAgICAxODYsXG4gICAgICAgIDk3LFxuICAgICAgICAxNSxcbiAgICAgICAgMTY5LFxuICAgICAgICAxMCxcbiAgICAgICAgMjAsXG4gICAgICAgIDMxLFxuICAgICAgICA2OCxcbiAgICAgICAgOTksXG4gICAgICAgIDQsXG4gICAgICAgIDYyLFxuICAgICAgICA2MyxcbiAgICAgICAgMjQ1LFxuICAgICAgICAxNTcsXG4gICAgICAgIDExMFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMixcbiAgICAgICAgMjQ2LFxuICAgICAgICAxNDUsXG4gICAgICAgIDQyLFxuICAgICAgICAyMzEsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMTM0LFxuICAgICAgICA0NyxcbiAgICAgICAgMTAzLFxuICAgICAgICAzNixcbiAgICAgICAgMTU2LFxuICAgICAgICAyMDYsXG4gICAgICAgIDE5NyxcbiAgICAgICAgOTcsXG4gICAgICAgIDMsXG4gICAgICAgIDE2MixcbiAgICAgICAgNzYsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMTE2LFxuICAgICAgICAxNTEsXG4gICAgICAgIDY2LFxuICAgICAgICAxOTAsXG4gICAgICAgIDE5NixcbiAgICAgICAgODAsXG4gICAgICAgIDg5LFxuICAgICAgICA1MixcbiAgICAgICAgMjMzLFxuICAgICAgICA1NCxcbiAgICAgICAgMjUxLFxuICAgICAgICAyNDEsXG4gICAgICAgIDI0NixcbiAgICAgICAgOTVcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIyNCxcbiAgICAgICAgOTIsXG4gICAgICAgIDkwLFxuICAgICAgICAyMDQsXG4gICAgICAgIDI0MyxcbiAgICAgICAgMjAyLFxuICAgICAgICAzNyxcbiAgICAgICAgMjM2LFxuICAgICAgICA1NixcbiAgICAgICAgMjQyLFxuICAgICAgICAxNzksXG4gICAgICAgIDQyLFxuICAgICAgICA4NixcbiAgICAgICAgMTQxLFxuICAgICAgICA4NixcbiAgICAgICAgMzUsXG4gICAgICAgIDc5LFxuICAgICAgICAyMjcsXG4gICAgICAgIDgsXG4gICAgICAgIDE4NixcbiAgICAgICAgMTIxLFxuICAgICAgICA4MyxcbiAgICAgICAgMjM5LFxuICAgICAgICA2MyxcbiAgICAgICAgMjcsXG4gICAgICAgIDE0NSxcbiAgICAgICAgMTczLFxuICAgICAgICA2MSxcbiAgICAgICAgMjU0LFxuICAgICAgICAyMDQsXG4gICAgICAgIDQ3LFxuICAgICAgICAxMjBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTMxLFxuICAgICAgICA5OSxcbiAgICAgICAgMjIxLFxuICAgICAgICA0NyxcbiAgICAgICAgMjIxLFxuICAgICAgICA1NixcbiAgICAgICAgMTkzLFxuICAgICAgICA3OSxcbiAgICAgICAgMTMyLFxuICAgICAgICA2OCxcbiAgICAgICAgNDUsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMTIsXG4gICAgICAgIDk2LFxuICAgICAgICAxMTAsXG4gICAgICAgIDE3NCxcbiAgICAgICAgMjIsXG4gICAgICAgIDg2LFxuICAgICAgICA1OSxcbiAgICAgICAgNjEsXG4gICAgICAgIDIwMixcbiAgICAgICAgMTUsXG4gICAgICAgIDIwNSxcbiAgICAgICAgNDIsXG4gICAgICAgIDEyLFxuICAgICAgICAyNTUsXG4gICAgICAgIDEwOCxcbiAgICAgICAgMTc0LFxuICAgICAgICAxOSxcbiAgICAgICAgMTU3LFxuICAgICAgICA0NCxcbiAgICAgICAgOTBcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDgwLFxuICAgICAgICAxMzAsXG4gICAgICAgIDEyOCxcbiAgICAgICAgMTA0LFxuICAgICAgICA0MSxcbiAgICAgICAgMTMxLFxuICAgICAgICAxNDksXG4gICAgICAgIDEyOCxcbiAgICAgICAgMjExLFxuICAgICAgICAxNjQsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMTU3LFxuICAgICAgICA5OCxcbiAgICAgICAgMjQxLFxuICAgICAgICAxMDMsXG4gICAgICAgIDYxLFxuICAgICAgICAyNDUsXG4gICAgICAgIDczLFxuICAgICAgICAxNjUsXG4gICAgICAgIDE1MyxcbiAgICAgICAgNjIsXG4gICAgICAgIDU1LFxuICAgICAgICAxOTcsXG4gICAgICAgIDIyOCxcbiAgICAgICAgNDEsXG4gICAgICAgIDEzMyxcbiAgICAgICAgNCxcbiAgICAgICAgMjIxLFxuICAgICAgICAxNixcbiAgICAgICAgMjI3LFxuICAgICAgICA3LFxuICAgICAgICA5OVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNCxcbiAgICAgICAgMjQsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMTU1LFxuICAgICAgICAxODAsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMjE1LFxuICAgICAgICA5NyxcbiAgICAgICAgMjgsXG4gICAgICAgIDU3LFxuICAgICAgICAxNixcbiAgICAgICAgMjIwLFxuICAgICAgICA3NixcbiAgICAgICAgMTk4LFxuICAgICAgICAxMDYsXG4gICAgICAgIDQ2LFxuICAgICAgICAxOTcsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMjYsXG4gICAgICAgIDgsXG4gICAgICAgIDc1LFxuICAgICAgICA5NCxcbiAgICAgICAgODgsXG4gICAgICAgIDEyLFxuICAgICAgICAxNDcsXG4gICAgICAgIDE2NCxcbiAgICAgICAgMTQ5LFxuICAgICAgICAxNDMsXG4gICAgICAgIDE5NixcbiAgICAgICAgMTkzLFxuICAgICAgICA5MCxcbiAgICAgICAgMjJcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNTYsXG4gICAgICAgICAgMTUyLFxuICAgICAgICAgIDgyLFxuICAgICAgICAgIDY5LFxuICAgICAgICAgIDE5MixcbiAgICAgICAgICAyMzYsXG4gICAgICAgICAgOTIsXG4gICAgICAgICAgMjI3LFxuICAgICAgICAgIDIzMyxcbiAgICAgICAgICAyMCxcbiAgICAgICAgICAyMjksXG4gICAgICAgICAgMTQ2LFxuICAgICAgICAgIDkwLFxuICAgICAgICAgIDE0OCxcbiAgICAgICAgICAyNDIsXG4gICAgICAgICAgNDksXG4gICAgICAgICAgNDUsXG4gICAgICAgICAgNDMsXG4gICAgICAgICAgMjMyLFxuICAgICAgICAgIDEwLFxuICAgICAgICAgIDE2MSxcbiAgICAgICAgICA3NCxcbiAgICAgICAgICA1MSxcbiAgICAgICAgICAxODUsXG4gICAgICAgICAgMTksXG4gICAgICAgICAgMTE4LFxuICAgICAgICAgIDE3MCxcbiAgICAgICAgICA1LFxuICAgICAgICAgIDI1MyxcbiAgICAgICAgICAyMzksXG4gICAgICAgICAgNjYsXG4gICAgICAgICAgMTAwXG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDE4LFxuICAgICAgICAgIDEwMixcbiAgICAgICAgICAxNDcsXG4gICAgICAgICAgMTcsXG4gICAgICAgICAgNjEsXG4gICAgICAgICAgMTA5LFxuICAgICAgICAgIDQ2LFxuICAgICAgICAgIDEwNyxcbiAgICAgICAgICAyMTEsXG4gICAgICAgICAgMjAxLFxuICAgICAgICAgIDIxMSxcbiAgICAgICAgICA5MyxcbiAgICAgICAgICAxMTAsXG4gICAgICAgICAgNDIsXG4gICAgICAgICAgMTQwLFxuICAgICAgICAgIDY1LFxuICAgICAgICAgIDI1MCxcbiAgICAgICAgICAyNDQsXG4gICAgICAgICAgMTc2LFxuICAgICAgICAgIDU0LFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICA2MyxcbiAgICAgICAgICAyMTIsXG4gICAgICAgICAgMTA3LFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDE1MixcbiAgICAgICAgICA5NCxcbiAgICAgICAgICAxMyxcbiAgICAgICAgICAxNjQsXG4gICAgICAgICAgMTY3LFxuICAgICAgICAgIDgwLFxuICAgICAgICAgIDg2XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTMzLFxuICAgICAgICAxNTcsXG4gICAgICAgIDgyLFxuICAgICAgICAxMjcsXG4gICAgICAgIDUzLFxuICAgICAgICAyNixcbiAgICAgICAgMTY5LFxuICAgICAgICAxMTgsXG4gICAgICAgIDE1OCxcbiAgICAgICAgODAsXG4gICAgICAgIDIzLFxuICAgICAgICAxOTgsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMTMyLFxuICAgICAgICAxNzQsXG4gICAgICAgIDI0MyxcbiAgICAgICAgMTA4LFxuICAgICAgICAzMSxcbiAgICAgICAgMjE1LFxuICAgICAgICAxOTgsXG4gICAgICAgIDE2NixcbiAgICAgICAgMjIyLFxuICAgICAgICAyNDIsXG4gICAgICAgIDI1LFxuICAgICAgICAxMzUsXG4gICAgICAgIDYxLFxuICAgICAgICAxNjIsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMTIxLFxuICAgICAgICA2OSxcbiAgICAgICAgMjI2LFxuICAgICAgICAxOTYsXG4gICAgICAgIDExOSxcbiAgICAgICAgNTgsXG4gICAgICAgIDE0NixcbiAgICAgICAgMTMwLFxuICAgICAgICAxODUsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMjM4LFxuICAgICAgICAyMjUsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMjU1LFxuICAgICAgICAzMyxcbiAgICAgICAgMTg1LFxuICAgICAgICAyMTksXG4gICAgICAgIDM4LFxuICAgICAgICAxODAsXG4gICAgICAgIDE5OSxcbiAgICAgICAgMTk3LFxuICAgICAgICAyMDYsXG4gICAgICAgIDI1LFxuICAgICAgICAyNyxcbiAgICAgICAgMzQsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMTMzLFxuICAgICAgICAyNSxcbiAgICAgICAgMjQ3LFxuICAgICAgICAxODAsXG4gICAgICAgIDkwLFxuICAgICAgICAyMDUsXG4gICAgICAgIDE4NCxcbiAgICAgICAgMTYxLFxuICAgICAgICAxOTUsXG4gICAgICAgIDEwXG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAyNTMsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiNXZNeDRiYTdFVm4ycVEyUE0rMnRUNENRUUFTMk9LRmlteWlTVGZIUEJJOD1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyMzQ3MDgwOTM2Mjg4QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI4OUVDRDYxNzBDM0MzNTY5REQxQ0FDQjE3MzExMjZBNVwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjcwMjIzNTlcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyMzQ3MDgwOTM2Mjg4QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIwMTg1MDQwMERDRjY0RTIxM0M4QUYyQjU3RjBFODFBQlwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjcwMjIzNjFcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiYnZKV0xoNlRRU3ktRFpqMldqMGpBUVwiLFxuICBcInBob25lSWRcIjogXCJjYTU4ZDc5Zi0wYTVjLTQ5ZjktODM2NC1hZTAyMzllZWIxNTRcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTU4LFxuICAgICAgMTQ0LFxuICAgICAgMzUsXG4gICAgICA3NixcbiAgICAgIDIwNixcbiAgICAgIDU3LFxuICAgICAgNjEsXG4gICAgICAzNCxcbiAgICAgIDE3MSxcbiAgICAgIDI0OSxcbiAgICAgIDcxLFxuICAgICAgMTg0LFxuICAgICAgMjI3LFxuICAgICAgMTAzLFxuICAgICAgMTQ5LFxuICAgICAgMTM2LFxuICAgICAgMTAzLFxuICAgICAgNDUsXG4gICAgICA5NCxcbiAgICAgIDEzNVxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAyMTksXG4gICAgICAyMDYsXG4gICAgICA0LFxuICAgICAgMTAzLFxuICAgICAgMzUsXG4gICAgICAyNDQsXG4gICAgICAyMzYsXG4gICAgICA4NixcbiAgICAgIDE4NCxcbiAgICAgIDE2MixcbiAgICAgIDE5MyxcbiAgICAgIDU0LFxuICAgICAgMTA1LFxuICAgICAgNDIsXG4gICAgICAyNTEsXG4gICAgICAxODAsXG4gICAgICAxNzksXG4gICAgICAxMDEsXG4gICAgICA5NCxcbiAgICAgIDEzXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIloxUkFWNkpDXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyMzQ3MDgwOTM2Mjg4OjRAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjE5NTI5Njg0MzgzNzQ2Mzo0QGxpZFwiLFxuICAgIFwibmFtZVwiOiBcIkZsYW1lcyDwn5GAIPCfpoUg8J+puiDwn5SlIOKdpO+4j+KdpOKAjfCflKVcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNLUzkxN1VHRUkyS3diY0dHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcImQ5ek1nRkhpb0pmYWdQSjdYSFM4dlR3ODdEeWJEZkFCeitDeUF6Ym1mQ289XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiY0FtOTNLekpiRUc5cXNncnh2Q2M1aTVuRWQ3TXR1RFJpeDBiOGxtaUtuQmYyalhEcWUxNTZEZkZnYnF3N2FDTmVoVzRwNEZCeW9TdTJNMENPaFI5Q3c9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwia1NZQTY4YlZjWXhBQXIwcnFiNW9SZ0lNM1lFUk5hMEMzMmVXdkNLdCtKOWpSTVZTYzJMby9kVDZWeXkxOXVWZks4Vnh0WVdIWmp6ZnJKNkwvR2RDRGc9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjM0NzA4MDkzNjI4ODo0QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMTE5LFxuICAgICAgICAgIDIyMCxcbiAgICAgICAgICAyMDQsXG4gICAgICAgICAgMTI4LFxuICAgICAgICAgIDgxLFxuICAgICAgICAgIDIyNixcbiAgICAgICAgICAxNjAsXG4gICAgICAgICAgMTUxLFxuICAgICAgICAgIDIxOCxcbiAgICAgICAgICAxMjgsXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDEyMyxcbiAgICAgICAgICA5MixcbiAgICAgICAgICAxMTYsXG4gICAgICAgICAgMTg4LFxuICAgICAgICAgIDE4OSxcbiAgICAgICAgICA2MCxcbiAgICAgICAgICA2MCxcbiAgICAgICAgICAyMzYsXG4gICAgICAgICAgNjAsXG4gICAgICAgICAgMTU1LFxuICAgICAgICAgIDEzLFxuICAgICAgICAgIDI0MCxcbiAgICAgICAgICAxLFxuICAgICAgICAgIDIwNyxcbiAgICAgICAgICAyMjQsXG4gICAgICAgICAgMTc4LFxuICAgICAgICAgIDMsXG4gICAgICAgICAgNTQsXG4gICAgICAgICAgMjMwLFxuICAgICAgICAgIDEyNCxcbiAgICAgICAgICA0MlxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzI3MDIyMzUzLFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBTjg2XCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFOODYuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJFLytxRmg4UE0yVHE5aTVwOEJocWhCbFp0R1ViaTRNRDN3ejJqdFBNdzJjPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE3MjMxOTUwNDQsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcyNzAyMjM1NzU4OFwifSIKfQ==",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
